### ISSUE TITLE
File->getDestination fails without extension

### ISSUE THREAD

**Issue by MGatner** [codeigniter4/CodeIgniter4#2103]
**Describe the bug**
Calling `$file->move()` and providing a new filename without an extension causes a failed array reference because `pathinfo()` does not have an extension key in the resulting array.

**CodeIgniter 4 version**
Latest develop

**Affected module(s)**
File Class, HTTPFile Class

**Context**
 - OS: Linux
 - Web server: Apache
 - PHP version: 7.2

**Comment by MGatner** [comment]
```
CRITICAL - 2019-07-24 15:38:09 --> Undefined index: extension
#0 ./vendor/codeigniter4/codeigniter4/system/Files/File.php(223): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', '/srv/web/...', 223, Array)
#1 ./vendor/codeigniter4/codeigniter4/system/HTTP/Files/UploadedFile.php(176): CodeIgniter\Files\File->getDestination('/srv/web/...')
#2 ./app/Controllers/Files.php(46): CodeIgniter\HTTP\Files\UploadedFile->move('/srv/web/...', 'noext')
#3 ./vendor/codeigniter4/codeigniter4/system/CodeIgniter.php(838): App\Controllers\Files->upload()
#4 ./vendor/codeigniter4/codeigniter4/system/CodeIgniter.php(335): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Files))
#5 ./vendor/codeigniter4/codeigniter4/system/CodeIgniter.php(245): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 ./public/index.php(45): CodeIgniter\CodeIgniter->run()
```
