### ISSUE TITLE
Bug:  &quot;Type is not supported&quot; in Postgresql POST restful

### ISSUE THREAD

**Issue by samsonasik** [codeigniter4/CodeIgniter4#2812]
I tried to create a restful api with POST data for create products and call:

```bash
 curl -i -X POST -d "product_code=A1114&product_name=Corn" http://ci4.local/products
```

and got the following errors:

```bash
HTTP/1.1 500 Internal Server Error
Date: Thu, 09 Apr 2020 01:13:21 GMT
Server: Apache/2.4.41 (Unix) PHP/7.4.4
X-Powered-By: PHP/7.4.4
Cache-control: no-store, max-age=0, no-cache
Content-Length: 2568
Connection: close
Content-Type: application/json; charset=UTF-8

<br />
<b>Fatal error</b>:  Uncaught CodeIgniter\Format\Exceptions\FormatException: Failed to parse json string, error: &quot;Type is not supported&quot;. in /Users/samsonasik/www/ci4/vendor/codeigniter4/codeigniter4/system/Format/Exceptions/FormatException.php:9
Stack trace:
#0 /Users/samsonasik/www/ci4/vendor/codeigniter4/codeigniter4/system/Format/JSONFormatter.php(67): CodeIgniter\Format\Exceptions\FormatException::forInvalidJSON('Type is not sup...')
#1 /Users/samsonasik/www/ci4/vendor/codeigniter4/codeigniter4/system/API/ResponseTrait.php(401): CodeIgniter\Format\JSONFormatter-&gt;format(Array)
#2 /Users/samsonasik/www/ci4/vendor/codeigniter4/codeigniter4/system/API/ResponseTrait.php(131): CodeIgniter\Debug\Exceptions-&gt;format(Array)
#3 /Users/samsonasik/www/ci4/vendor/codeigniter4/codeigniter4/system/Debug/Exceptions.php(165): CodeIgniter\Debug\Exceptions-&gt;respond(Array, 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions-&gt;exceptionHandler(Object(ErrorException))
#5 {main}
  thrown in <b>/Users/samsonasik/www/ci4/vendor/codeigniter4/codeigniter4/system/Format/Exceptions/FormatException.php</b> on line <b>9</b><br />
{
    "title": "ErrorException",
    "type": "ErrorException",
    "code": 500,
    "message": "Uncaught CodeIgniter\\Format\\Exceptions\\FormatException: Failed to parse json string, error: \"Type is not supported\". in /Users/samsonasik/www/ci4/vendor/codeigniter4/codeigniter4/system/Format/Exceptions/FormatException.php:9\nStack trace:\n#0 /Users/samsonasik/www/ci4/vendor/codeigniter4/codeigniter4/system/Format/JSONFormatter.php(67): CodeIgniter\\Format\\Exceptions\\FormatException::forInvalidJSON('Type is not sup...')\n#1 /Users/samsonasik/www/ci4/vendor/codeigniter4/codeigniter4/system/API/ResponseTrait.php(401): CodeIgniter\\Format\\JSONFormatter->format(Array)\n#2 /Users/samsonasik/www/ci4/vendor/codeigniter4/codeigniter4/system/API/ResponseTrait.php(131): CodeIgniter\\Debug\\Exceptions->format(Array)\n#3 /Users/samsonasik/www/ci4/vendor/codeigniter4/codeigniter4/system/Debug/Exceptions.php(165): CodeIgniter\\Debug\\Exceptions->respond(Array, 500)\n#4 [internal function]: CodeIgniter\\Debug\\Exceptions->exceptionHandler(Object(ErrorException))\n#5 {main}\n  thrown",
    "file": "/Users/samsonasik/www/ci4/vendor/codeigniter4/codeigniter4/system/Format/Exceptions/FormatException.php",
    "line": 9,
    "trace": [
        {
            "function": "shutdownHandler",
            "class": "CodeIgniter\\Debug\\Exceptions",
            "type": "->",
            "args": []
        }
    ]
}%                                                   
```

My controller is like the following:

```php
<?php namespace App\Controllers;

use CodeIgniter\RESTful\ResourceController;

class Products extends ResourceController
{
    protected $modelName = 'App\Models\ProductModel';
    protected $format    = 'json';

    public function create()
    {
        $data = $this->request->getPost();

        if (! $this->model->save($data))
        {
            return $this->respond($this->model->errors());

        }

        return $this->respondCreated($data, 'product created');
    }
}
```

I switched to mysql and it is working fine.

**CodeIgniter 4 version**
latest dev-develop

**Affected module(s)**
Database

**Expected behavior, and steps to reproduce if appropriate**
should be working

**Context**
 - OS: macOS Sierra
 - Web server Apache
 - PHP version 7.4.4

**Comment by samsonasik** [comment]
After some check, it related with parsing validation rule string in Postgresql environment ( in Mysql it is working). Here is my model:

```php
<?php namespace App\Models;

use App\Entities\Product;
use CodeIgniter\Model;

class ProductModel extends Model
{
	protected $table           = 'product';
	protected $returnType      = Product::class;
	protected $allowedFields   = [
		'product_code',
		'product_name',
	];
	protected $validationRules = [
		'product_code' => 'required|alpha_numeric|exact_length[5]|is_unique[product.product_code,id,{id}]',
		'product_name' => 'required|alpha_numeric_space|min_length[3]|max_length[255]|is_unique[product.product_name,id,{id}]',
	];
}
```

I changed the `$validationRules` with only "required" make it work:

```php
		'product_code' => 'required',
		'product_name' => 'required',
```

**Comment by samsonasik** [comment]
I got that in Postgresql, validation rules like :

```php
is_unique[product.product_code,id,{id}]
```

is not working.

**Comment by samsonasik** [comment]
The bug is came from the following line : 

https://github.com/codeigniter4/CodeIgniter4/blob/7179fcc6c004a6f30aca07ca94355b750e78523e/system/Validation/Rules.php#L231

**Comment by samsonasik** [comment]
This issue seems still persist in API request at Postgresql in version 4.0.3, while in non-API, it is working fine.
