### ISSUE TITLE
Bug:  table.Array in first() ... - and complex primary keys! ;-)

### ISSUE THREAD

**Issue by nowackipawel** [codeigniter4/CodeIgniter4#3394]
I will try to fix it in next days because I know exactly where the error is.
No issue:
```

				$user_exam = (new \User2DrivingSchoolModel())
					->where('usr2drs_usr_id', $usr_id)
					->where('usr2drs_drs_id', (int)$this->request->getGet('drs_id'))
					->groupStart()->where('usr2drs_dlc_id IS NULL', null, false)->orWhere('usr2drs_dlc_id', strtoupper($dlc_id_or_qus_id))->groupEnd()
					->orderBy('usr2drs_dlc_id', 'ASC')
					->first();
```
Issue exists:
```

				$user_exam = (new \User2DrivingSchoolModel())
					->where('usr2drs_usr_id', $usr_id)
					->where('usr2drs_drs_id', (int)$this->request->getGet('drs_id'))
					->groupStart()->where('usr2drs_dlc_id IS NULL', null, false)->orWhere('usr2drs_dlc_id', strtoupper($dlc_id_or_qus_id))->groupEnd()
					->first();
```
and error:
```
CRITICAL - 2020-07-23 17:49:18 --> Unknown column 't_user2t_driving_school.Array' in 'order clause'
#0 /home/zdamy/site/system/Database/MySQLi/Connection.php(330): mysqli->query()
#1 /home/zdamy/site/system/Database/BaseConnection.php(738): CodeIgniter\Database\MySQLi\Connection->execute()
#2 /home/zdamy/site/system/Database/BaseConnection.php(666): CodeIgniter\Database\BaseConnection->simpleQuery()
#3 /home/zdamy/site/system/Database/BaseBuilder.php(1820): CodeIgniter\Database\BaseConnection->query()
#4 /home/zdamy/site/system/Model.php(516): CodeIgniter\Database\BaseBuilder->get()
#5 /home/zdamy/site/app/Controllers/Site/CPracticeTest.php(156): CodeIgniter\Model->first()
#6 /home/zdamy/site/system/CodeIgniter.php(910): App\Controllers\Site\CPracticeTest->index()
#7 /home/zdamy/site/system/CodeIgniter.php(398): CodeIgniter\CodeIgniter->runController()
#8 /home/zdamy/site/system/CodeIgniter.php(306): CodeIgniter\CodeIgniter->handleRequest()
#9 /home/zdamy/site/public/index.php(45): CodeIgniter\CodeIgniter->run()
#10 {main}
```

It is related to this part:
```

		// Some databases, like PostgreSQL, need order
		// information to consistently return correct results.
		if (empty($builder->QBOrderBy) && ! empty($this->primaryKey))
		{
			$builder->orderBy($this->table . '.' . $this->primaryKey, 'asc');
		}
```
of first() method .

**Comment by michalsn** [comment]
I'm pretty sure that your primary key is an array. Sorry, but composite primary keys are not supported at this moment.

I'm closing this, but feel free to continue the conversation.

**Comment by nowackipawel** [comment]
#4120
