### ISSUE TITLE
Bug:  method_exists(): Argument #1 ($object_or_class) must be of type object|string On PHP 8

### ISSUE THREAD

**Issue by uzairali001** [codeigniter4/CodeIgniter4#4898]
**Describe the bug**
When using php 8 it throws error  `method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given`
Stack:
```
CRITICAL - 2021-07-02 02:56:34 --> method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given
#0 x:\Laragon\api\login\v5\system\BaseModel.php(1744): method_exists(NULL, 'select')
#1 x:\Laragon\api\login\v5\system\Model.php(796): CodeIgniter\BaseModel->__call('select', Array)
#2 x:\Laragon\api\login\v5\app\Models\User\AppUserModel.php(130): CodeIgniter\Model->__call('select', Array)
```

**CodeIgniter 4 version**
4.1.3

**Context**
 - OS: Win10
 - Web server Apache 2.4.35
 - PHP version 8.0.22

**Edit**
```
// AppUserModel.php
<?php

namespace App\Models\User;

use CodeIgniter\Model;
use \App\Libraries\UAuth;

class AppUserModel extends Model
{
    protected $table = 'app_user';
    protected $primaryKey = 'app_user_id';
    protected $allowedFields = [
        'user_level_id', 'user_name', 'user_email', 'app_password', 'is_active',
        'is_deleted', 'is_banned'
    ];

    private $selectFields = [
        'app_user.app_user_id', 'app_user.user_uuid', 'app_user.client_id',
        'app_user.user_name', 'app_user.user_email', 'app_user.app_password', 'app_user.is_active',
        'app_user.is_deleted', 'app_user.is_banned', 'ban_message',
    ];

    public function __construct()
    {
    }
    
    ...

    public function getByEmailPassword($emailAddress, $password)
    {
        $user = $this->select($selectFields)
            ->join('user_level ul', 'app_user.user_level_id = ul.user_level_id')
            ->getWhere(['app_user.user_email' => $emailAddress, 'app_user.is_active' => 1, 'app_user.is_deleted' => 0])
            ->getRow();

            ...

    }
```

**Edit 2**
Issue resolves when I add `$this->builder($this->table)` when building query.
Is this how it's suppose to work or it's just a bug?
```
$user = $this->builder($this->table)
            ->select($selectFields)
            ->join('user_level ul', 'app_user.user_level_id = ul.user_level_id')
            ->getWhere(['app_user.user_email' => $emailAddress, 'app_user.is_active' => 1, 'app_user.is_deleted' => 0])
            ->getRow();
```

**Comment by paulbalandan** [comment]
Can you show the code of AppUserModel?

**Comment by uzairali001** [comment]
@paulbalandan Updated, also want to let you know that the same code is working on PHP 7

**Comment by paulbalandan** [comment]
Sorry to be unclear. Can you show the constructor part of your model?

**Comment by paulbalandan** [comment]
This is not a bug. In cases where you are extending a parent class and you are defining your own constructor, you should also call the parent's constructor. The Model's constructor initializes the $db and $validation properties. In your case, you are explicitly overwriting the constructor that's why those were never initialized.
