### ISSUE TITLE
Bug: Too many errors - website stopped working

### ISSUE THREAD

**Issue by amirandev** [codeigniter4/CodeIgniter4#6072]
### PHP Version

7.4

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL 5.6

### What happened?

Everything workd fine unless I completed my project and uploadet to my web server. 
I changed envirnonmetn **development** to **production** I got that error:
![image](https://user-images.githubusercontent.com/73018912/172003681-8639b955-c639-4415-9843-ab0285ec4437.png)

### Steps to Reproduce

Than I changed envirnonmetn **development** to **production**  on my localhost and "**damn... what a hell is whong with it?**"
I opened the logs file and to my surprise it said that $query is not an object and other stupid errors. 

```
function sys($out, $table = 'default'){
....
$model = new SysMeta();
$query = $model->where('id', 1)->asObject()->first();
return strlen($query->$out) < 5 ? asset('assets/images/ogimage.png') : $query->$out;
```
Than I removed the query and it told me that there was not that offset which means that database connection was unavailable couse this function gets parameter from my databse  but in last log update it changed it's maind ;)

```
function metarobots($out = ''){
    $out = trim($out);
    $arr = [
        1 => 'All',
        2 => 'noindex',
        3 => 'nofollow',
        4 => 'noindex,nofollow'
    ];
    
    return $out == '' ? $arr : $arr[$out]; 
}

```

**Now, This is how my logs file looks like:**
 ```

CRITICAL - 2022-06-04 18:03:20 --> Undefined offset: 0
#0 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\Router\RouteCollection.php(1091): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', 'C:\\xampp\\htdocs...', 1091, Array)
#1 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\Router\RouteCollection.php(971): CodeIgniter\Router\RouteCollection->fillRouteParams('profile/view(.*...', Array)
#2 C:\xampp\htdocs\tones.to\app\Helpers\general_helper.php(234): CodeIgniter\Router\RouteCollection->reverseRoute('my_profile')
#3 C:\xampp\htdocs\tones.to\app\Views\partials\header.php(21): route('my_profile', Array)
#4 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\View\View.php(438): CodeIgniter\View\View->render('partials/header', NULL, true)
#7 C:\xampp\htdocs\tones.to\app\Views\layouts\default.php(27): CodeIgniter\View\View->include('partials/header')
#8 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#10 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\View\View.php(226): CodeIgniter\View\View->render('layouts/default', Array, true)
#11 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\Common.php(1099): CodeIgniter\View\View->render('index/index', Array, true)
#12 C:\xampp\htdocs\tones.to\app\Controllers\Home.php(45): view('index/index', Array)
#13 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\CodeIgniter.php(834): App\Controllers\Home->index()
#14 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#15 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\tones.to\index.php(40): CodeIgniter\CodeIgniter->run()
#17 {main}
CRITICAL - 2022-06-04 18:03:22 --> Undefined offset: 0
#0 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\Router\RouteCollection.php(1091): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', 'C:\\xampp\\htdocs...', 1091, Array)
#1 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\Router\RouteCollection.php(971): CodeIgniter\Router\RouteCollection->fillRouteParams('profile/view(.*...', Array)
#2 C:\xampp\htdocs\tones.to\app\Helpers\general_helper.php(234): CodeIgniter\Router\RouteCollection->reverseRoute('my_profile')
#3 C:\xampp\htdocs\tones.to\app\Views\partials\header.php(21): route('my_profile', Array)
#4 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\View\View.php(438): CodeIgniter\View\View->render('partials/header', NULL, true)
#7 C:\xampp\htdocs\tones.to\app\Views\layouts\default.php(27): CodeIgniter\View\View->include('partials/header')
#8 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#10 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\View\View.php(226): CodeIgniter\View\View->render('layouts/default', Array, true)
#11 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\Common.php(1099): CodeIgniter\View\View->render('index/index', Array, true)
#12 C:\xampp\htdocs\tones.to\app\Controllers\Home.php(45): view('index/index', Array)
#13 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\CodeIgniter.php(834): App\Controllers\Home->index()
#14 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#15 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\tones.to\index.php(40): CodeIgniter\CodeIgniter->run()
#17 {main}
CRITICAL - 2022-06-04 18:03:24 --> Undefined offset: 0
#0 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\Router\RouteCollection.php(1091): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', 'C:\\xampp\\htdocs...', 1091, Array)
#1 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\Router\RouteCollection.php(971): CodeIgniter\Router\RouteCollection->fillRouteParams('profile/view(.*...', Array)
#2 C:\xampp\htdocs\tones.to\app\Helpers\general_helper.php(234): CodeIgniter\Router\RouteCollection->reverseRoute('my_profile')
#3 C:\xampp\htdocs\tones.to\app\Views\partials\header.php(21): route('my_profile', Array)
#4 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\View\View.php(438): CodeIgniter\View\View->render('partials/header', NULL, true)
#7 C:\xampp\htdocs\tones.to\app\Views\layouts\default.php(27): CodeIgniter\View\View->include('partials/header')
#8 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\View\View.php(210): include('C:\\xampp\\htdocs...')
#9 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#10 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\View\View.php(226): CodeIgniter\View\View->render('layouts/default', Array, true)
#11 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\Common.php(1099): CodeIgniter\View\View->render('index/index', Array, true)
#12 C:\xampp\htdocs\tones.to\app\Controllers\Home.php(45): view('index/index', Array)
#13 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\CodeIgniter.php(834): App\Controllers\Home->index()
#14 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#15 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 C:\xampp\htdocs\tones.to\index.php(40): CodeIgniter\CodeIgniter->run()
#17 {main}

```

### Expected Output

Expected a well designed which working properly would be outputed

**Comment by iRedds** [comment]
Show what data you are passing to the ``route`` function
Views\partials\header.php(21): route('my_profile', Array)

**Comment by kenjis** [comment]
> Everything workd fine unless I completed my project and uploadet to my web server.
I changed envirnonmetn development to production I got that error:

Do you mean if the environment is `development`, your site works fine on your web server?

**Comment by amirandev** [comment]
> > Everything workd fine unless I completed my project and uploadet to my web server.
> > I changed envirnonmetn development to production I got that error:
> 
> Do you mean if the environment is `development`, your site works fine on your web server?
Yeah, if the environment is development, my site works fine on my hosting server

**Comment by kenjis** [comment]
@amirandev Frankly, I can't imagine why it would stop working at all just by changing `development` to `production`.

The log you put seems to be log on your local PC (XAMPP).
On your hositng server, are the errors the same?

> CRITICAL - 2022-06-04 18:03:20 --> Undefined offset: 0
#0 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\Router\RouteCollection.php(1091): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', 'C:\\xampp\\htdocs...', 1091, Array)

Also, what exactly is the following code?

> Views\partials\header.php(21): route('my_profile', Array)

**Comment by amirandev** [comment]
> @amirandev Frankly, I can't imagine why it would stop working at all just by changing `development` to `production`.
> 
> The log you put seems to be log on your local PC (XAMPP). On your hositng server, are the errors the same?
> 
> > CRITICAL - 2022-06-04 18:03:20 --> Undefined offset: 0
> > #0 C:\xampp\htdocs\tones.to\vendor\codeigniter4\framework\system\Router\RouteCollection.php(1091): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', 'C:\xampp\htdocs...', 1091, Array)
> 
> Also, what exactly is the following code?
> 
> > Views\partials\header.php(21): route('my_profile', Array)

The hosting errors are less than XAMPP errors. You can see my error log from hosting.
```
CRITICAL - 2022-06-04 12:34:18 --> Call to undefined function App\Controllers\imageCompress()
#0 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/CodeIgniter.php(834): App\Controllers\FileController->Upload()
#1 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\FileController))
#2 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 /home/vol5_8/byethost11.com/b11_31812891/htdocs/index.php(40): CodeIgniter\CodeIgniter->run()
#4 {main}
```

It says "Call to undefined function App\Controllers\imageCompress()" and I agree with it bit it's a helper function and you know... this error is out of sence.
Also as you can see it has chashing problem even I chmoded the directories.

**Comment by deicool** [comment]
Hi

Can you please paste the code of "App\Controllers\FileController->Upload()"?

Thanks!

**Comment by amirandev** [comment]
> Hi
> 
> Can you please paste the code of "App\Controllers\FileController->Upload()"?
> 
> Thanks!
Sure
```
public function Upload()
{
        $validationRule = [
            'upload_file' => [
                'label' => 'The file',
                'rules' => 'uploaded[upload_file]' . 
                '|UploadsDisabled['.sys('enable_uploads', 'upload').', 1]' . 
                '|ext_in[upload_file, '.rts(sys('exts_allowed', 'upload')).']'.
                '|max_size[upload_file,'.rts(sys('max_upload_mb', 'upload')).']'. 
                '|min_dims[upload_file,'.rts(sys('img_min_w', 'upload')).','.rts(sys('img_min_h', 'upload')).']'. 
                '|max_dims[upload_file,'.rts(sys('img_max_w', 'upload')).','.rts(sys('img_max_h', 'upload')).']'.
                '|'.screenRuletrow().'[upload_file]'
            ],
        ];
 
        // '.rts().'
        
        if (!$this->validate($validationRule) || sys('enable_uploads', 'upload') == 0 || letUpload() == false) {
            
            $outErr = sys('enable_uploads', 'upload') == 0 
            ? 'Oops, for some reasons file uploads are disabled by website administration.' 
            : (letUpload() == false ? letUpload('message') : $this->validator->getError('upload_file'));
            
            return $this->response->json([
                'message' => $outErr,
                'status' => 0
            ]);
        }
        
        $file = $this->request->getFile('upload_file');
        $ext = $file->getClientExtension();
		$randomName = $file->getRandomName();
		$data['fileName'] = $file->getName();
		$data['randomName'] = $randomName;
		$data['fileType'] = $file->getClientMimeType();
		$data['fileSize'] = $file->getSize();
         
        $outFolderName = extPath($ext);       
        $title = str_replace('.'.$ext, '', $data['fileName']);
        
        // title size correction
        $title = strlen($title) > sys('max_item_title') ? substr($title, 0, sys('max_item_title')) : $title;
        
        $file->move('storage/'.extPath($ext), $randomName);
        
        if($outFolderName == 'wallpapers'){
            if($ext == 'png' || $ext == 'jpg' || $ext == 'jpeg' || $ext == 'gif'){
                $fpath = Storage::get('wallpapers/'.$randomName);
                // compress
                imageCompress($fpath);
            }
        }
        
        // auto moderation
		$auto_moderation = (int)protect(sys('auto_moderation'));
        
        $model = new ItemModel();
        $model->save([
            'file' => trim($randomName),
            'user_id'  => myid(),
            'title'  => protect($title),
            'color' => randLightColor(),
            'kind' => $kind,
            'moderated' => $auto_moderation,
            'created_at' => now(),
            'updated_at' => now()
        ]);

        $lastID = $model->getInsertID();
        if(my('notify_moderations') == 1){
            if($auto_moderation == 0):
                sendNotification(myid(), 0, $lastID, 'Your item is under moderation quee', route('view_profile',[myid(), st(my('username'))]));
            else:
                sendNotification(myid(), 0, $lastID, 'Your item has been approved');
            endif;
        }
        
        return $this->response->json([
            'message' => 'The file uploaded successfully',
            'status' => 1,
            'kind' => KindName($kind),
            'id' => $lastID
        ]);
}
```

**Comment by deicool** [comment]
Where is the function (imageCompress) defined? It is being used in the function upload.

Call to undefined function App\Controllers\imageCompress()

**Comment by amirandev** [comment]
> Where is the function (imageCompress) defined? It is being used in the function upload.
> 
> Call to undefined function App\Controllers\imageCompress()

function imageCompress($file, $quality = 9) {
    $saveTo = $file;
    $ext = pathinfo($file, PATHINFO_EXTENSION);
    $img_info = getimagesize($file);
    list($w, $h) = $img_info;
    $mime = $img_info['mime'];
    
    if($mime == 'image/png'){
        $tmp = imageResizeLayer(imagecreatefrompng($file), $w, $h, $w, $h);
        $run = imagepng($tmp, $saveTo, $quality);
    }
    elseif($mime == 'image/jpeg'){
        $tmp = imageResizeLayer(imagecreatefromjpeg($file), $w, $h, $w, $h);
        $run = imagejpeg($tmp, $saveTo, $quality);
    }
    elseif($mime == 'image/gif'){
        $tmp = imageResizeLayer(imagecreatefromgif($file), $w, $h, $w, $h);
        $run = imagegif($tmp, $saveTo, $quality);
    }
}

**Comment by deicool** [comment]
I didn't ask the contents of the method imageCompress().

I asked where is it being defined?

**Comment by amirandev** [comment]
The thing is if I set **SHOW_DEBUG_BACKTRACE** to **false** everitings uppsets
defined('SHOW_DEBUG_BACKTRACE') || define('SHOW_DEBUG_BACKTRACE', false);

![image](https://user-images.githubusercontent.com/73018912/172054591-1d02abf6-1956-44fb-b887-47104fb992fa.png)

```
CRITICAL - 2022-06-05 18:02:51 --> Undefined offset: 0
#0 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/Router/RouteCollection.php(1091): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', '/home/vol5_8/by...', 1091, Array)
#1 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/Router/RouteCollection.php(971): CodeIgniter\Router\RouteCollection->fillRouteParams('profile/view(.*...', Array)
#2 /home/vol5_8/byethost11.com/b11_31812891/htdocs/app/Helpers/general_helper.php(234): CodeIgniter\Router\RouteCollection->reverseRoute('my_profile')
#3 /home/vol5_8/byethost11.com/b11_31812891/htdocs/app/Views/partials/header.php(21): route('my_profile', Array)
#4 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/View/View.php(210): include('/home/vol5_8/by...')
#5 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/View/View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/View/View.php(438): CodeIgniter\View\View->render('partials/header', NULL, true)
#7 /home/vol5_8/byethost11.com/b11_31812891/htdocs/app/Views/layouts/default.php(27): CodeIgniter\View\View->include('partials/header')
#8 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/View/View.php(210): include('/home/vol5_8/by...')
#9 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/View/View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#10 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/View/View.php(226): CodeIgniter\View\View->render('layouts/default', Array, true)
#11 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/Common.php(1099): CodeIgniter\View\View->render('index/index', Array, true)
#12 /home/vol5_8/byethost11.com/b11_31812891/htdocs/app/Controllers/Home.php(45): view('index/index', Array)
#13 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/CodeIgniter.php(834): App\Controllers\Home->index()
#14 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#15 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 /home/vol5_8/byethost11.com/b11_31812891/htdocs/index.php(40): CodeIgniter\CodeIgniter->run()
#17 {main}
```

Now I will clear the log and set it to set **SHOW_DEBUG_BACKTRACE** to **true** and let's see what will happen.

![image](https://user-images.githubusercontent.com/73018912/172054768-2b0cd512-3f84-41de-a9e4-f74ef7b92d26.png)

Now I will clear logs again and cache too:
Cache is empty
Debuger cache is empty
Cleared sessions
Deleted log file
Refresh page

**Result**:

```
CRITICAL - 2022-06-05 18:16:31 --> Undefined offset: 0
#0 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/Router/RouteCollection.php(1091): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined offse...', '/home/vol5_8/by...', 1091, Array)
#1 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/Router/RouteCollection.php(971): CodeIgniter\Router\RouteCollection->fillRouteParams('profile/view(.*...', Array)
#2 /home/vol5_8/byethost11.com/b11_31812891/htdocs/app/Helpers/general_helper.php(234): CodeIgniter\Router\RouteCollection->reverseRoute('my_profile')
#3 /home/vol5_8/byethost11.com/b11_31812891/htdocs/app/Views/partials/header.php(21): route('my_profile', Array)
#4 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/View/View.php(210): include('/home/vol5_8/by...')
#5 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/View/View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#6 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/View/View.php(438): CodeIgniter\View\View->render('partials/header', NULL, true)
#7 /home/vol5_8/byethost11.com/b11_31812891/htdocs/app/Views/layouts/default.php(27): CodeIgniter\View\View->include('partials/header')
#8 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/View/View.php(210): include('/home/vol5_8/by...')
#9 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/View/View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#10 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/View/View.php(226): CodeIgniter\View\View->render('layouts/default', Array, true)
#11 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/Common.php(1099): CodeIgniter\View\View->render('index/index', Array, true)
#12 /home/vol5_8/byethost11.com/b11_31812891/htdocs/app/Controllers/Home.php(45): view('index/index', Array)
#13 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/CodeIgniter.php(834): App\Controllers\Home->index()
#14 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#15 /home/vol5_8/byethost11.com/b11_31812891/htdocs/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#16 /home/vol5_8/byethost11.com/b11_31812891/htdocs/index.php(40): CodeIgniter\CodeIgniter->run()
#17 {main}



```

**Comment by amirandev** [comment]
> I didn't ask the contents of the method imageCompress().
> 
> I asked where is it being defined?

app/helpers/GeneralHelper.php

**Comment by deicool** [comment]
Your code is trying to find the method imageCompress() in "App\Controllers\imageCompress()"

**Comment by amirandev** [comment]
> Your code is trying to find the method imageCompress() in "App\Controllers\imageCompress()"

Let's see my new logs above

**Comment by kenjis** [comment]
It seems it is not a framework bug.

We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
