### ISSUE TITLE
Bug: spark not working if directory path contains parentheses

### ISSUE THREAD

**Issue by schlagmichdoch** [codeigniter4/CodeIgniter4#6190]
### PHP Version

7.4

### CodeIgniter4 Version

4.2.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MySQL 8.0

### What happened?

When the directoy path contains paranthesis anywhere `composer install` still works fine but any `php spark` command throws the following error:

``` log
PHP Fatal error:  Uncaught Error: Class 'Config\App' not found in C:\Users\domin\software_development(local)\project-root\system\Config\Config.php:157
Stack trace:
#0 C:\Users\domin\software_development(local)\project-root\system\Config\Config.php(83): CodeIgniter\Config\Config::createClass('Config\\App')
#1 C:\Users\domin\software_development(local)\project-root\system\Common.php(155): CodeIgniter\Config\Config::get('Config\\App', true)
#2 C:\Users\domin\software_development(local)\project-root\system\bootstrap.php(179): config('Config\\App')
#3 C:\Users\domin\software_development(local)\project-root\spark(44): require('C:\\Users\\domin\\...')
#4 {main}
  thrown in C:\Users\domin\software_development(local)\project-root\system\Config\Config.php on line 157

Fatal error: Uncaught Error: Class 'Config\App' not found in C:\Users\domin\software_development(local)\project-root\system\Config\Config.php:157
Stack trace:
#0 C:\Users\domin\software_development(local)\project-root\system\Config\Config.php(83): CodeIgniter\Config\Config::createClass('Config\\App')
#1 C:\Users\domin\software_development(local)\project-root\system\Common.php(155): CodeIgniter\Config\Config::get('Config\\App', true)
#2 C:\Users\domin\software_development(local)\project-root\system\bootstrap.php(179): config('Config\\App')
#3 C:\Users\domin\software_development(local)\project-root\spark(44): require('C:\\Users\\domin\\...')
#4 {main}
  thrown in C:\Users\domin\software_development(local)\project-root\system\Config\Config.php on line 157
```

This seems to be common behaviour under linux but is unexpected on windows. Quick search seems like the path could simply be escaped to make it working:

https://unix.stackexchange.com/questions/125776/error-with-a-file-name-containing-parentheses

Not sure whether this is codeigniter specific and whether it is even possible to make it change, but it would be nice. Otherwise it would be great if you could add a note specifying the naming convention to https://codeigniter4.github.io/userguide/installation/installing_composer.html#installation-set-up

### Steps to Reproduce

1. create folder containing paranthesis (e.g. `software(locale)`)
2. create codeigniter project inside with `composer create-project codeigniter4/appstarter project-root`
3. execute php spark serve inside

### Expected Output

working php spark without error no matter where codeigniter is installed

**Comment by kenjis** [comment]
Oh, I can reproduce.

```console
$ php spark serve
PHP Fatal error:  Uncaught Error: Class "Config\App" not found in /Users/kenji/tmp/software(locale)/project-root/vendor/codeigniter4/framework/system/Config/Factories.php:126
Stack trace:
#0 /Users/kenji/tmp/software(locale)/project-root/vendor/codeigniter4/framework/system/Common.php(198): CodeIgniter\Config\Factories::__callStatic('config', Array)
#1 /Users/kenji/tmp/software(locale)/project-root/vendor/codeigniter4/framework/system/Config/Services.php(143): config('App')
#2 /Users/kenji/tmp/software(locale)/project-root/vendor/codeigniter4/framework/system/Config/BaseService.php(251): CodeIgniter\Config\Services::codeigniter(NULL, false)
#3 /Users/kenji/tmp/software(locale)/project-root/vendor/codeigniter4/framework/system/Config/BaseService.php(192): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#4 /Users/kenji/tmp/software(locale)/project-root/vendor/codeigniter4/framework/system/Config/Services.php(140): CodeIgniter\Config\BaseService::getSharedInstance('codeigniter', NULL)
#5 /Users/kenji/tmp/software(locale)/project-root/vendor/codeigniter4/framework/system/Config/BaseService.php(251): CodeIgniter\Config\Services::codeigniter()
#6 /Users/kenji/tmp/software(locale)/project-root/spark(70): CodeIgniter\Config\BaseService::__callStatic('codeigniter', Array)
#7 {main}
  thrown in /Users/kenji/tmp/software(locale)/project-root/vendor/codeigniter4/framework/system/Config/Factories.php on line 126

Fatal error: Uncaught Error: Class "Config\App" not found in /Users/kenji/tmp/software(locale)/project-root/vendor/codeigniter4/framework/system/Config/Factories.php on line 126

Error: Class "Config\App" not found in /Users/kenji/tmp/software(locale)/project-root/vendor/codeigniter4/framework/system/Config/Factories.php on line 126

Call Stack:
    0.0010     402336   1. {main}() /Users/kenji/tmp/software(locale)/project-root/spark:0
    0.0113    1749712   2. CodeIgniter\Config\BaseService::codeigniter() /Users/kenji/tmp/software(locale)/project-root/spark:70
    0.0113    1749712   3. CodeIgniter\Config\BaseService::__callStatic($name = 'codeigniter', $arguments = []) /Users/kenji/tmp/software(locale)/project-root/spark:70
    0.0140    1826576   4. CodeIgniter\Config\Services::codeigniter($config = ???, $getShared = ???) /Users/kenji/tmp/software(locale)/project-root/vendor/codeigniter4/framework/system/Config/BaseService.php:251
    0.0140    1826576   5. CodeIgniter\Config\BaseService::getSharedInstance($key = 'codeigniter', ...$params = variadic(NULL)) /Users/kenji/tmp/software(locale)/project-root/vendor/codeigniter4/framework/system/Config/Services.php:140
    0.0140    1826952   6. CodeIgniter\Config\BaseService::codeigniter(NULL, FALSE) /Users/kenji/tmp/software(locale)/project-root/vendor/codeigniter4/framework/system/Config/BaseService.php:192
    0.0140    1827328   7. CodeIgniter\Config\BaseService::__callStatic($name = 'codeigniter', $arguments = [0 => NULL, 1 => FALSE]) /Users/kenji/tmp/software(locale)/project-root/vendor/codeigniter4/framework/system/Config/BaseService.php:192
    0.0140    1827328   8. CodeIgniter\Config\Services::codeigniter($config = NULL, $getShared = FALSE) /Users/kenji/tmp/software(locale)/project-root/vendor/codeigniter4/framework/system/Config/BaseService.php:251
    0.0140    1827328   9. config($name = 'App', $getShared = ???) /Users/kenji/tmp/software(locale)/project-root/vendor/codeigniter4/framework/system/Config/Services.php:143
    0.0140    1827704  10. CodeIgniter\Config\Factories::config('App', ['getShared' => TRUE]) /Users/kenji/tmp/software(locale)/project-root/vendor/codeigniter4/framework/system/Common.php:198
    0.0140    1828080  11. CodeIgniter\Config\Factories::__callStatic($component = 'config', $arguments = [0 => 'App', 1 => ['getShared' => TRUE]]) /Users/kenji/tmp/software(locale)/project-root/vendor/codeigniter4/framework/system/Common.php:198
```

**Comment by kenjis** [comment]
I sent a PR #6192
