### ISSUE TITLE
Bug: New line detected in headers sent

### ISSUE THREAD

**Issue by najdanovicivan** [codeigniter4/CodeIgniter4#6782]
### PHP Version

8.1

### CodeIgniter4 Version

4.2.7

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

fpm-fcgi

### Database

Mysql 5.6

### What happened?

I'm getting this error in the log

```
CRITICAL - 2022-10-27 17:15:29 --> Uncaught ErrorException: Header may not contain more than a single header, new line detected in /home/dsf/web/vendor/codeigniter4/framework/system/HTTP/ResponseTrait.php:475
Stack trace:
#0 /home/dsf/web/core_modules/Debug/Exceptions.php(51): CodeIgniter\Debug\Exceptions->errorHandler()
#1 [internal function]: Debug\Exceptions->errorHandler()
#2 /home/dsf/web/vendor/codeigniter4/framework/system/HTTP/ResponseTrait.php(475): header()
#3 /home/dsf/web/vendor/codeigniter4/framework/system/HTTP/ResponseTrait.php(445): CodeIgniter\HTTP\Response->sendHeaders()
#4 /home/dsf/web/vendor/codeigniter4/framework/system/Debug/Exceptions.php(132): CodeIgniter\HTTP\Response->send()
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler()
#6 {main}
  thrown
in SYSTEMPATH/HTTP/ResponseTrait.php on line 475.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
```

### Steps to Reproduce

I am unable to reproduce the issue manually. I happens rarely. The site is serving hundred thousands requests daly and I'm not seeing the issue every days. It happens only on some days once or twice. 

What would be the best way to get more details on the issue. I can only add some additional logging so that we can follow the where the new line was outputted before the issue happens.

Looking at the stack trace I don't see any of my custom code being loaded. So it has to be somewhere in the CI classes. 

### Expected Output

The critical error should not happen

### Anything else?

Using 
Nginx + Php 8.1 with PHP-FPM on AlmaLinux 9 but i was noticing the same issue with CentOS 7 and php7.X/8.0 setup. So it should not be related to PHP version

**Comment by paulbalandan** [comment]
In line 475 of ResponseTrait, can you add a `log_message` before that containing the value of the headers to be sent so that we can see which particular header causes this issue.

**Comment by najdanovicivan** [comment]
@paulbalandan this will make the log go crazy as sendHeaders is called on every response. I was thinking of checking for the message errorHandler for example md5($message . $file . $line) and if md5 matches I log from service('response')->headers()

Does this make sense ?

**Comment by paulbalandan** [comment]
Yeah, my suggestion was crazy to begin with. Sure. Anything that can help us identify the erring header.

**Comment by kenjis** [comment]
> Header may not contain more than a single header, new line detected

What about logging only when a new line is included?

**Comment by paulbalandan** [comment]
@najdanovicivan do you have updates on this?

**Comment by paulbalandan** [comment]
Closing for no activity.

**Comment by najdanovicivan** [comment]
I've finally managed to find the reason why the issue happens.

I have search form on the site which send POST request and then cals the $response->redirect which returns to the GET route with search term in the URL.

When I sanitised the term I did not strip the new line characters from the URL.  So response redirect() method was getting url with multiple lines which in the end set the `Location` header with multiple lines.  Location should url encoded so that new line is handled as `%0D%0A`

There are a couple of things that can be done:
-     pass url to urlencode() in response->redirect() method
-     replace new line characters with spaces in Header object constructor so that there is no possibility to have multi line header values
-     Ignore all of these and just add notice in the docs that new line characters should be handled prior to calling redirect() method

**Comment by kenjis** [comment]
`setHeader()` should not accept new line code. It should throws an exception.

> Field values containing CR, LF, or NUL characters are invalid and dangerous, due to the varying ways that implementations might parse and interpret those characters; a recipient of CR, LF, or NUL within a field value MUST either reject the message or replace each of those characters with SP before further processing or forwarding of that message. Field values containing other CTL characters are also invalid; however, recipients MAY retain such characters for the sake of robustness when they appear within a safe context (e.g., an application-specific quoted string that will not be processed by any downstream HTTP parser).
https://www.rfc-editor.org/rfc/rfc9110#section-5.5
