### ISSUE TITLE
Bug: [Session] Uncaught mysqli_sql_exception: Duplicate entry 'ci_session:***' for key 'ci_sessions.PRIMARY'

### ISSUE THREAD

**Issue by JamesShaver** [codeigniter4/CodeIgniter4#7585]
### PHP Version

8.1

### CodeIgniter4 Version

4.3.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

mysql  Ver 8.0.33-0ubuntu0.22.04.2 for Linux on x86_64 ((Ubuntu))

### What happened?

While in Development mode:
```
Fatal error
: Uncaught mysqli_sql_exception: Duplicate entry 'ci_session:ug4g9pdf1275sccvc1sjn62hdtmsgnvt' for key 'ci_sessions.PRIMARY' 
in /var/www/codeigniter/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:295 
Stack trace: 
#0 /var/www/codeigniter/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(295): mysqli->query() 
#1 /var/www/codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute() 
#2 /var/www/codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery() 
#3 /var/www/codeigniter/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query() 
#4 /var/www/codeigniter/vendor/codeigniter4/framework/system/Session/Handlers/DatabaseHandler.php(208): CodeIgniter\Database\BaseBuilder->insert() 
#5 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->write() 
#6 [internal function]: session_write_close() 
#7 {main} 
Next CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'ci_session:ug4g9pdf1275sccvc1sjn62hdtmsgnvt' for key 'ci_sessions.PRIMARY' 
in /var/www/codeigniter/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:300 
Stack trace: 
#0 /var/www/codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute() 
#1 /var/www/codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery() 
#2 /var/www/codeigniter/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query() 
#3 /var/www/codeigniter/vendor/codeigniter4/framework/system/Session/Handlers/DatabaseHandler.php(208): CodeIgniter\Database\BaseBuilder->insert() 
#4 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->write() 
#5 [internal function]: session_write_close() 
#6 {main} 
Next CodeIgniter\Database\Exceptions\DatabaseException: Duplicate entry 'ci_session:ug4g9pdf1275sccvc1sjn62hdtmsgnvt' for key 'ci_sessions.PRIMARY' 
in /var/www/codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php:646 
Stack trace: 
#0 /var/www/codeigniter/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query() 
#1 /var/www/codeigniter/vendor/codeigniter4/framework/system/Session/Handlers/DatabaseHandler.php(208): CodeIgniter\Database\BaseBuilder->insert() 
#2 [internal function]: CodeIgniter\Session\Handlers\DatabaseHandler->write() 
#3 [internal function]: session_write_close() 
#4 {main} thrown in
/var/www/codeigniter/vendor/codeigniter4/framework/system/Database/BaseConnection.php
on line
646
```

### Steps to Reproduce

I am running CodeIgniter through a local NAS (http://home-nas) in development mode.  Periodically, the errors listed above show up in the footer of the site.  I am able to truncate the ci_sessions table, and the error is not displayed again for some time.

### Expected Output

No error.  If the session ID already exists either use it, or drop it and create a new session.

**Comment by kenjis** [comment]
Can you show the session table definition and the `$matchIP` setting in `Config\Session`?

**Comment by JamesShaver** [comment]
@kenjis, sure, here you go:

```
CREATE TABLE `ci_sessions` (
  `id` varchar(128) NOT NULL,
  `ip_address` varchar(45) NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data` blob NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

ALTER TABLE `ci_sessions`
  ADD PRIMARY KEY (`id`),
  ADD KEY `timestamp` (`timestamp`);
```
public bool $matchIP = true;

**Comment by michalsn** [comment]
Your primary key is incorrect. Run this to fix it.

```sql
ALTER TABLE ci_sessions DROP PRIMARY KEY;
ALTER TABLE ci_sessions ADD PRIMARY KEY (id, ip_address);
```

You can read more in the user guide: https://www.codeigniter.com/user_guide/libraries/sessions.html#configure-databasehandler
