### ISSUE TITLE
Bug: Crash on php 8.4 on TimeTrait::createFromTimestamp() usage

### ISSUE THREAD

**Issue by samsonasik** [codeigniter4/CodeIgniter4#9348]
### PHP Version

8.4

### CodeIgniter4 Version

4.5.6

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### What happened?

I just tried latest CodeIgniter 4.5.6 in my module, and in php 8.4, it cause error:

```
 Runtime:       PHP 8.4.2 with Xdebug 3.5.0-dev
Configuration: /home/runner/work/ci4-album/ci4-album/phpunit.xml.dist

PHP Fatal error:  Declaration of CodeIgniter\I18n\TimeTrait::createFromTimestamp(int $timestamp, $timezone = null, ?string $locale = null) must be compatible with DateTimeImmutable::createFromTimestamp(int|float $timestamp): static in /home/runner/work/ci4-album/ci4-album/vendor/codeigniter4/framework/system/I18n/TimeTrait.php on line 268
PHP Fatal error:  Uncaught Error: Class "CodeIgniter\I18n\Time" not found in /home/runner/work/ci4-album/ci4-album/vendor/codeigniter4/framework/system/HTTP/ResponseTrait.php:398
Stack trace:
#0 /home/runner/work/ci4-album/ci4-album/vendor/codeigniter4/framework/system/HTTP/ResponseTrait.php(376): CodeIgniter\HTTP\Response->sendHeaders()
#1 /home/runner/work/ci4-album/ci4-album/vendor/codeigniter4/framework/system/Debug/ExceptionHandler.php(83): CodeIgniter\HTTP\Response->send()
#2 /home/runner/work/ci4-album/ci4-album/vendor/codeigniter4/framework/system/Debug/Exceptions.php(162): CodeIgniter\Debug\ExceptionHandler->handle()
#3 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler()
#4 {main}
  thrown in /home/runner/work/ci4-album/ci4-album/vendor/codeigniter4/framework/system/HTTP/ResponseTrait.php on line 398
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
Fatal error: Declaration of CodeIgniter\I18n\TimeTrait::createFromTimestamp(int $timestamp, $timezone = null, ?string $locale = null) must be compatible with DateTimeImmutable::createFromTimestamp(int|float $timestamp): static in /home/runner/work/ci4-album/ci4-album/vendor/codeigniter4/framework/system/I18n/TimeTrait.php on line 268

Fatal error: Uncaught Error: Class "CodeIgniter\I18n\Time" not found in /home/runner/work/ci4-album/ci4-album/vendor/codeigniter4/framework/system/HTTP/ResponseTrait.php:398
Stack trace:
#0 /home/runner/work/ci4-album/ci4-album/vendor/codeigniter4/framework/system/HTTP/ResponseTrait.php(376): CodeIgniter\HTTP\Response->sendHeaders()
#1 /home/runner/work/ci4-album/ci4-album/vendor/codeigniter4/framework/system/Debug/ExceptionHandler.php(83): CodeIgniter\HTTP\Response->send()
#2 /home/runner/work/ci4-album/ci4-album/vendor/codeigniter4/framework/system/Debug/Exceptions.php(162): CodeIgniter\Debug\ExceptionHandler->handle()
#3 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler()
#4 {main}
  thrown in /home/runner/work/ci4-album/ci4-album/vendor/codeigniter4/framework/system/HTTP/ResponseTrait.php on line 398
```

https://github.com/samsonasik/ci4-album/actions/runs/12532301581/job/34950890792?pr=19

see PR: https://github.com/samsonasik/ci4-album/pull/19

### Steps to Reproduce

at github action above.

### Expected Output

should not crash.

**Comment by samsonasik** [comment]
see https://3v4l.org/5rcSN , return type seems also needed to be changed to static, see without return type https://3v4l.org/INmps and with full param and return type changed https://3v4l.org/JOMF1

**Comment by kenjis** [comment]
PHP 8.4 requires CodeIgniter 4.6.0 or later. See #9116

**Comment by samsonasik** [comment]
Ok, closing then ;)
